DROP TABLE IF EXISTS billionaires;
 
CREATE TABLE billionaires (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);
 
INSERT INTO billionaires (first_name, last_name, career) VALUES
  ('Aliko', 'Dangote', 'Billionaire Industrialist'),
  ('Bill', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('Folrunsho', 'Alakija', 'Billionaire Oil Magnate');
  
DROP TABLE IF EXISTS employee;
   
 CREATE TABLE  employee  (
  id int generated by default as identity (start with 1) primary key,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) DEFAULT NULL,
);


INSERT INTO employee (id, name, description) VALUES
  ('1', 'Dangote', 'Billionaire Industrialist'),
  ('2', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('3', 'Alakija', 'Billionaire Oil Magnate');