DROP TABLE IF EXISTS billionaires;
 
CREATE TABLE billionaires (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);
 
INSERT INTO billionaires (first_name, last_name, career) VALUES
  ('Aliko', 'Dangote', 'Billionaire Industrialist'),
  ('Bill', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('Folrunsho', 'Alakija', 'Billionaire Oil Magnate');
  
   
 CREATE TABLE  employee  (
  id int generated by default as identity (start with 1) primary key,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) DEFAULT NULL,
);


INSERT INTO employee (id, name, description) VALUES
  ('1', 'Allen','Dangote', 'Billionaire Industrialist'),
  ('2', 'Mark','Gates', 'Water Tech Ball'),
  ('3', 'Sam','John', 'Information Technologies'),
  ('4', 'Mark','Gates', 'Sell Tech Entrepreneur'),
  ('5', 'Tom','Alakija', 'Best Oil Magnate');